# k8s/02-monitor/tempo/values.yaml
tempo:
  receivers:
    otlp:
      protocols:
        # Explicitly enable the HTTP receiver on port 4318
        http:
          endpoint: 0.0.0.0:4318
        # Explicitly enable the gRPC receiver on port 4317
        grpc:
          endpoint: 0.0.0.0:4317